### ISSUE TITLE
Npm picks wrong angular version?

### ISSUE THREAD

**Issue by wil93** [algorithm-ninja/cmsocial#10]
If I issue `make` I get angular 1.5 even though there's `"angular": "^1.4.8"` in the `package.json` file.

If I issue `make PROD=1` I correctly get a link to angular 1.4.8

**Comment by lucach** [comment]
`angular@^1.4.8` translates to `angular@>=1.4.8 <2.0.0` ([docs](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004)).
