### ISSUE TITLE
Adding a new tag permission

### ISSUE THREAD

**Issue by alessandro-bugatti** [algorithm-ninja/cmsocial#15]
I tried to add a new tag to a problem (semiprimo), wondering that it would not be possible. Instead I added a new tag, a wrong one ("abc" in this case), and when I tried to delete it, it was not possible because I was unauthorized. I think there is something wrong in this behaviour, what do you think?

**Comment by wil93** [comment]
The normal behavior is: the user who added the tag can remove it unless the tag has been approved (in this case, it was not), so yes, there is something wrong... I noticed a bug which was introduced not long ago, and maybe I fixed it in 739d54e69cabd0d2479b32a840aafd052326acd5. Do you still have issues when removing a tag?

**Comment by alessandro-bugatti** [comment]
Ok, now it works, thanks.

**Comment by alessandro-bugatti** [comment]
By the way, I removed the wrong tag I added in "semiprimo"

**Comment by wil93** [comment]
Perfect, thanks for the report :smile:
