### ISSUE TITLE
The profile picture covers the user page (mobile)

### ISSUE THREAD

**Issue by wil93** [algorithm-ninja/cmsocial#2]
![0b179e2e5af305e8737dc6c09f043e48d682140f](https://cloud.githubusercontent.com/assets/1285361/11626059/0932f876-9ce0-11e5-9421-0ed340754489.png)

as reported [here](http://cms.di.unipi.it:8000/t/visualizzazione-profili-da-mobile/408).

**Comment by lucach** [comment]
PR #23 attempts to fix - or, at least, does a reasonable approximation of a proper fix - this bug.

**Comment by lucach** [comment]
This specific issue has been addressed in dbf88ace2a1a6aad7f77e8eb64f3bdc3c960fb2c. I think we can now close this.
We'll open separate issues if any CSS-related problem arise in the future.
