### ISSUE TITLE
Auth cookie has neither Expire nor Max-Age header

### ISSUE THREAD

**Issue by lucach** [algorithm-ninja/cmsocial#25]
The authentication cookie is setted [here](https://github.com/algorithm-ninja/cmsocial/blob/develop/cmsocial/server/pws.py#L658-L660) without specifying `max_age` and `expires` parameters, which default to `null`.

This causes the cookie to expire at the end of the browser session, which is not a desirable behaviour ([reference from werkzeug code](https://github.com/pallets/werkzeug/blob/master/werkzeug/wrappers.py#L1040-L1042)).

A common setting is 30 days. Note that there is not the concept of "infinity", but we could set a date far in the future.

**Comment by veluca93** [comment]
Well, that would explain things. I don't know why I never noticed this so far...

**Comment by lucach** [comment]
I decided to investigate this because I was continuously logged out.
However, cookie expiration time - as per RFC - is marked with "SHOULD". Maybe this is the reason why we see browsers behaving differently :thinking:
