### ISSUE TITLE
Errore con la mia password al login di CMS

### ISSUE THREAD

**Issue by eutampieri** [algorithm-ninja/cmsocial#5]
![cattura](https://cloud.githubusercontent.com/assets/10284268/12238682/9013dd40-b885-11e5-8d04-3da0933e1b2f.PNG) Non prende la mia password ma solo quella di priva ritornando errore 500.
```
{"action":"login","username":"eutampieri","password":"**$###********"}
```
Scusate ma ho mascherato la password:
* * = lettera minuscola
* $ = carattere speciale
* # = numero

**Comment by wil93** [comment]
Mmm non ho capito tu avevi modificato la password e ora non prende quella nuova?

**Comment by wil93** [comment]
Il problema dovrebbe essere risolto, confermi? :smile: (se non fosse così, riapri pure la issue)

**Comment by eutampieri** [comment]
Perfetto!
